### ISSUE TITLE
Quest_template entry 155 and all escorting missions!

### ISSUE THREAD

**Issue by tsui110** [mangosArchives/databaseZero_Rel19#145] opened 2013-12-18 15:35 UTC
Quest 155, after accepting the mission I can't speak to NPC who will start the mission!
All the escorting missions will complete without escorting NPC!

**Comment by billy1arm** [comment] 2014-04-02 09:22
Duplicate of #144 - closing

**Closed as completed by billy1arm** 2014-04-02 09:22 UTC
